### ISSUE TITLE
error[E0308]: mismatched types

### ISSUE THREAD

**Issue by hackerb9** [IrishBumfuzzle/sub.idx-convert-to-srt#1]
When I tried `cargo build --release`, I got the following error:

```error
   Compiling sub-to-srt v0.1.1
error[E0308]: mismatched types
  --> src/main.rs:27:34
   |
27 |         let mut img: RgbaImage = sub.to_image(idx.palette());
   |                      ---------   ^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected struct `ImageBuffer`, found struct `image::buffer::ImageBuffer`
   |                      |
   |                      expected due to this
   |
   = note: expected struct `ImageBuffer<Rgba<u8>, Vec<u8>>`
              found struct `image::buffer::ImageBuffer<image::color::Rgba<u8>, Vec<u8>>`

For more information about this error, try `rustc --explain E0308`.
error: could not compile `sub-to-srt` due to previous error
```

I'm using rustc 1.59.0 and cargo 1.56.0.

**Comment by IrishBumfuzzle** [comment]
Hi, can you verify that you have the image version v0.13.0 in your dependencies? I had the same problem a while back and I updated the toml.

Edit - Yep, that's the problem. And I see that you are a commit behind, updating it will fix the issue.

**Comment by hackerb9** [comment]
Thanks. That fixed it. I'm not sure how I got a release behind since I had only just cloned the repository yesterday. Which reminds me, the instructions in the README say to use `git pull`, but for most people it'll be `git clone`.

**Comment by IrishBumfuzzle** [comment]
Aah, yes thank you. Fixed.
